swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/login:
    post:
      tags:
        - User Module
      summary: Login
      description: API for Login
      parameters:
        - in: body
          name: body
          description: Login Payload
          required: true
          schema:
            $ref: '#/definitions/Login'
      produces:
        - application/json
      responses:
        '200':
          description: Login Successfully
          schema:
            $ref: '#/definitions/LoginResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/signup:
    post:
      tags:
        - User Module
      summary: Signup
      description: API for Signup
      parameters:
        - in: body
          name: body
          description: Signup Payload
          required: true
          schema:
            $ref: '#/definitions/User'
      produces:
        - application/json
      responses:
        '200':
          description: Signup Successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /user/profile:
    post:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for fetching a user profile
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
      produces:
        - application/json
      responses:
        '200':
          description: User profile retrieved successully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - User Module
      summary: User Profile API
      description: API for updating a user profile
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: body
          name: body
          description: Update user profile attributes
          required: true
          schema:
            $ref: '#/definitions/UserProfile'
      produces:
        - application/json
      responses:
        '200':
          description: User profile updated successfully
          schema:
            $ref: '#/definitions/ApiResponse'
        '400':
          description: Invalid Fields
        '500':
          description: Internal Server Error

  /account/{id}/transactions:
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Transactions Current Month API
      description: Retrieve all transactions of an account for a specific month
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: path
          name: id
          type: string
          required: true
          description: Account unique identifier
        - in: query
          name: month
          type: string
          default: "2026-07"
          required: false
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/allTransactionsResponse'
        '400':
          description: Invalid Fields
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
  /transactions/{id}/infos:
    post:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Add Transaction API
      description: API for adding a new transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          type: string
          required: true
          description: Account unique identifier
        - in: body
          name: body
          description: Transaction data to create
          required: true
          schema:
            $ref: '#/definitions/Transaction'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction created successfully
        '400':
          description: Invalid Fields
        '404':
          description: Account not found
        '500':
          description: Internal Server Error
    get:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Show Transaction API
      description: API for showing a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          required: true
        - in: path
          name: id
          type: string
          required: true
          description: Transaction unique identifier
      produces:
        - application/json
      responses:
        '200':
          description: Transactions retrieved successfully
          schema:
            $ref: '#/definitions/Transaction'
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    put:
      security:
        - Bearer: []
      tags:
        - Transactions Module
      summary: Update Transaction API
      description: API for updating a transaction
      parameters:
        - in: header
          name: Authorization
          type: string
          description: Attach Bearer JWT token
          required: true
        - in: path
          name: id
          type: string
          required: true
          description: ID of the transaction
        - in: body
          name: body
          description: Transaction information to update
          required: true
          schema:
            $ref: '#/definitions/TransactionUpdate'
      produces:
        - application/json
      responses:
        '200':
          description: Transaction updated successfully
          schema:
            $ref: '#/definitions/TransactionUpdate'
        '400':
          description: Invalid Fields
        '404':
          description: Transaction not found
        '500':
          description: Internal Server Error
    delete:
        security:
          - Bearer: []
        tags:
          - Transactions Module
        summary: Delete Transaction API
        description: API for deleting a transaction
        parameters:
          - in: header
            name: Authorization
            type: string
            description: Attach Bearer JWT token
            required: true
          - in: path
            name: id
            type: string
            required: true
            description: ID of the transaction
        produces:
          - application/json
        responses:
          '204':
           description: Transaction deleted successfully
          '404':
            description: Transaction not found
          '500':
            description: Internal Server Error

securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  User:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
      firstName:
        type: string
        description: user first name
      lastName:
        type: string
        description: user last name
  Login:
    properties:
      email:
        type: string
        description: user email
      password:
        type: string
        description: user password
  ApiResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          id:
            type: string
          email:
            type: string
  LoginResponse:
    type: object
    properties:
      token:
        type: string
  UserProfile:
    type: object
    properties:
      firstName:
        type: string
      lastName:
        type: string
  Transaction:
    type: object
    properties:
      id:
        type: string
        description: Unique transaction identifier
      date:
        type: string
        description: Transaction date
      description:
        type: string
        description: Transaction description
      amount:
        type: number
        description: Transaction amount
      balance:
        type: number
        description: Account balance after this transaction
      category:
        type: string
        description: Transaction category
      note:
        type: string
        description: User's note about the transaction
  TransactionUpdate:
    type: object
    properties:
      category:
        type: string
        description: Transaction category
      note:
        type: string
        description: User's note about the transaction
  allTransactionsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          $ref: '#/definitions/Transaction'